[theme]
theme = "slick"
[icons]
icons = "awesome6"

[theme.overrides]
idle_fg = "#A9A9A9"
idle_bg = "#181818"
info_bg = "#0078d4"
alternating_tint_fg = "#000000"
alternating_tint_bg = "#000000"

[[block]]
block = "weather"
format = " $icon Mikkeli $temp$wind m/s $direction $humidity "
interval = 600
autolocate = false
autolocate_interval = "once"
[block.service]
name = "metno"
coordinates = ["61.68857", "27.27227"]

[[block]]
block = "disk_space"
info_type = "available"
alert_unit = "GB"
alert = 5.0
warning = 7.0
format = " $icon $available "
format_alt = " $icon $available / $total "

[[block]]
block = "net"
format = " $icon ^icon_net_down $speed_down.eng(prefix:M) ^icon_net_up $speed_up.eng(prefix:M) "
format_alt = " $icon {$signal_strength $ssid $ip|$ip} $device "

[[block]]
block = "nvidia_gpu"
format = " $icon $utilization $temperature "

[[block]]
block = "cpu"
format = " $icon $utilization "
format_alt = " $icon $barchart "

[[block]]
block = "temperature"
interval = 10
format = " $icon "
format_alt = " $min min, $max max, $average avg "
chip = "coretemp-isa-0000"

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
step_width = 1

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "